import React from 'react';
import { Check } from './check';
import { cn } from '@/lib/utils';

export const HeroIllustration: React.FC = () => (
  <div className="relative w-full max-w-2xl mx-auto">
    {/* card */}
    <div className="rounded-3xl bg-white/80 backdrop-blur border border-violet-100 shadow-[0_10px_40px_rgba(109,40,217,0.15)] p-6">
      <div className="flex flex-col md:flex-row gap-6 items-center">
        {/* QR placeholder */}
        <div className="flex h-40 w-40 items-center justify-center rounded-2xl border border-slate-200 bg-white">
          <div className="grid grid-cols-5 gap-1 p-3">
            {Array.from({ length: 25 }).map((_, i) => (
              <div key={i} className={cn("h-3 w-3 rounded-sm", i % 3 === 0 ? "bg-violet-700" : "bg-violet-200")} />
            ))}
          </div>
        </div>
        {/* verified panel */}
        <div className="flex-1">
          <div className="flex items-center gap-2">
            <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-emerald-100 text-emerald-700">
              <Check stroke="currentColor" />
            </span>
            <span className="text-sm font-semibold text-emerald-700">Verified in 42s</span>
          </div>
          <h4 className="mt-2 text-lg font-semibold text-slate-800">Candidate summary</h4>
          <p className="text-slate-600 text-sm">
            Clear, role-aligned insights generated by AI. No personal data on-chain. Proof anchored on Bitcoin.
          </p>
          <div className="mt-3 flex flex-wrap gap-2 text-xs">
            <span className="rounded-full bg-violet-100 text-violet-700 px-2.5 py-1">Portable credential</span>
            <span className="rounded-full bg-violet-100 text-violet-700 px-2.5 py-1">Revocable</span>
            <span className="rounded-full bg-violet-100 text-violet-700 px-2.5 py-1">Expiry set</span>
          </div>
        </div>
      </div>
    </div>
    {/* glow */}
    <div className="pointer-events-none absolute inset-0 -z-10 rounded-[28px] bg-gradient-to-r from-violet-200 via-fuchsia-200 to-indigo-200 blur-2xl opacity-60" />
  </div>
);
